#!/usr/bin/env node

import * as readline from "readline";
import * as fs from "fs";
import * as path from "path";
import * as os from "os";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PROJECT_DIR = path.resolve(__dirname, "..");

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

function ask(question) {
  return new Promise((resolve) => rl.question(question, resolve));
}

function clear() {
  process.stdout.write("\x1b[2J\x1b[H");
}

function bold(text) {
  return `\x1b[1m${text}\x1b[0m`;
}
function dim(text) {
  return `\x1b[2m${text}\x1b[0m`;
}
function green(text) {
  return `\x1b[32m${text}\x1b[0m`;
}
function cyan(text) {
  return `\x1b[36m${text}\x1b[0m`;
}
function yellow(text) {
  return `\x1b[33m${text}\x1b[0m`;
}

async function main() {
  clear();
  console.log(bold("\n  Slack Aggregator Setup\n"));
  console.log(
    "  See all your Slack notifications from every workspace in one place.\n"
  );
  console.log(dim("  This wizard will walk you through connecting your Slack"));
  console.log(dim("  workspaces and creating a terminal shortcut.\n"));

  await ask(dim("  Press Enter to begin..."));

  // Step 1: Cookie
  clear();
  console.log(bold("\n  Step 1: Get your Slack cookie\n"));
  console.log("  1. Open " + cyan("https://app.slack.com") + " in your browser");
  console.log("  2. Open DevTools: " + cyan("Cmd+Option+I") + dim(" (Mac)") + " or " + cyan("F12") + dim(" (Windows)"));
  console.log("  3. Go to the " + cyan("Application") + " tab");
  console.log("  4. In the left sidebar, click " + cyan("Cookies") + " > " + cyan("https://app.slack.com"));
  console.log("  5. Find the cookie named " + cyan('"d"'));
  console.log("  6. Double-click the " + bold("Value") + " column and copy it\n");
  console.log(dim("  It starts with xoxd-...\n"));

  const cookie = (await ask("  Paste your cookie value: ")).trim();
  if (!cookie) {
    console.log("\n  Cookie is required. Run setup again when ready.");
    process.exit(1);
  }

  // Step 2: Workspaces
  clear();
  console.log(bold("\n  Step 2: Add your Slack workspaces\n"));
  console.log("  Now we need the token and team info for each workspace.\n");
  console.log("  In the same browser with Slack open, open the " + cyan("Console") + " tab");
  console.log("  and run this command:\n");
  console.log(
    cyan(
      '    JSON.parse(localStorage.getItem("localConfig_v2")).teams'
    )
  );
  console.log(
    dim(
      "\n  This shows all your workspace IDs, names, and tokens."
    )
  );
  console.log(
    dim(
      "  If it returns null, switch to a workspace tab first and try again.\n"
    )
  );
  console.log("  For each workspace, you'll need:");
  console.log("    - " + bold("Token") + dim(" (xoxc-...)"));
  console.log("    - " + bold("Team ID") + dim(" (T...)"));
  console.log("    - " + bold("Name") + dim(" (e.g. My Company)"));
  console.log("    - " + bold("Domain") + dim(" (the .slack.com subdomain)\n"));

  console.log(
    dim("  Tip: In the Console output, each workspace shows:\n")
  );
  console.log(dim("    id: \"T043N2KS0HW\"       ← Team ID"));
  console.log(dim("    name: \"MediaBuyer.com\"   ← Name"));
  console.log(dim("    domain: \"mediabuyercom\"  ← Domain"));
  console.log(dim("    token: \"xoxc-...\"        ← Token\n"));

  const workspaces = [];
  let addMore = true;

  while (addMore) {
    const num = workspaces.length + 1;
    console.log(bold(`\n  --- Workspace ${num} ---\n`));

    const name = (await ask("  Workspace name: ")).trim();
    if (!name) break;

    const teamId = (await ask("  Team ID (T...): ")).trim();
    const token = (await ask("  Token (xoxc-...): ")).trim();
    const domain = (await ask("  Domain (subdomain.slack.com): ")).trim();

    if (!teamId || !token || !domain) {
      console.log(yellow("\n  Skipping — all fields are required."));
      continue;
    }

    const key = name
      .toLowerCase()
      .replace(/[^a-z0-9]/g, "")
      .slice(0, 20);

    workspaces.push({ key, name, teamId, token, domain });
    console.log(green(`\n  Added ${name}!`));

    const more = (
      await ask("\n  Add another workspace? (y/n): ")
    )
      .trim()
      .toLowerCase();
    addMore = more === "y" || more === "yes";
  }

  if (workspaces.length === 0) {
    console.log("\n  No workspaces added. Run setup again when ready.");
    process.exit(1);
  }

  // Step 3: Generate .env.local
  clear();
  console.log(bold("\n  Step 3: Saving configuration...\n"));

  let env = `# Slack Notification Aggregator - Configuration
# Generated by setup wizard

# Shared cookie (from browser DevTools → Application → Cookies → "d")
SLACK_COOKIE_D=${cookie}

# Workspaces
SLACK_WORKSPACES=${workspaces.map((w) => w.key).join(",")}
`;

  for (const w of workspaces) {
    const KEY = w.key.toUpperCase();
    env += `
# ${w.name}
SLACK_TOKEN_${KEY}=${w.token}
SLACK_TEAM_ID_${KEY}=${w.teamId}
SLACK_TEAM_NAME_${KEY}=${w.name}
SLACK_TEAM_DOMAIN_${KEY}=${w.domain}
`;
  }

  const envPath = path.join(PROJECT_DIR, ".env.local");
  fs.writeFileSync(envPath, env);
  console.log(green("  Saved .env.local with " + workspaces.length + " workspace(s)"));

  // Step 4: Terminal alias
  clear();
  console.log(bold("\n  Step 4: Create a terminal shortcut\n"));
  console.log("  This adds a command to launch the app from any terminal.\n");

  const aliasName = (
    (await ask("  Command name (e.g. slack, notifs): ")) || "slack"
  )
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, "");

  // Detect shell config file
  const shell = process.env.SHELL || "/bin/zsh";
  let rcFile;
  if (shell.includes("zsh")) {
    rcFile = path.join(os.homedir(), ".zshrc");
  } else if (shell.includes("bash")) {
    // macOS uses .bash_profile, Linux uses .bashrc
    const bashProfile = path.join(os.homedir(), ".bash_profile");
    rcFile = fs.existsSync(bashProfile)
      ? bashProfile
      : path.join(os.homedir(), ".bashrc");
  } else {
    rcFile = path.join(os.homedir(), ".profile");
  }

  const funcBlock = `
# Slack Aggregator
${aliasName}() {
  local dir="${PROJECT_DIR}"
  local lock="$dir/.next/dev/lock"
  if [ -f "$lock" ]; then
    local lock_pid=$(cat "$lock" 2>/dev/null)
    [ -n "$lock_pid" ] && kill "$lock_pid" 2>/dev/null
    rm -f "$lock"
    sleep 1
  fi
  cd "$dir"
  local port=$(node -e "const s=require('net').createServer();s.listen(0,()=>{console.log(s.address().port);s.close()})")
  echo "Starting Slack Aggregator on port $port..."
  npm run dev -- -p "$port" &
  sleep 2
  open "http://localhost:$port" 2>/dev/null || xdg-open "http://localhost:$port" 2>/dev/null
}
`;

  // Check if alias already exists
  const rcContent = fs.existsSync(rcFile)
    ? fs.readFileSync(rcFile, "utf-8")
    : "";

  if (rcContent.includes("# Slack Aggregator")) {
    // Replace existing block
    const updated = rcContent.replace(
      /\n# Slack Aggregator\n[\s\S]*?\n}\n/,
      funcBlock
    );
    fs.writeFileSync(rcFile, updated);
    console.log(green(`  Updated existing alias in ${rcFile}`));
  } else {
    fs.appendFileSync(rcFile, funcBlock);
    console.log(green(`  Added '${aliasName}' command to ${rcFile}`));
  }

  // Done
  clear();
  console.log(bold("\n  Setup complete!\n"));
  console.log(
    `  ${green(">")} ${workspaces.length} workspace${workspaces.length > 1 ? "s" : ""} configured`
  );
  console.log(
    `  ${green(">")} Terminal command: ${cyan(aliasName)}\n`
  );
  console.log("  To start, either:\n");
  console.log(`    1. Open a new terminal and type ${cyan(aliasName)}`);
  console.log(
    `    2. Run ${cyan(`source ${rcFile}`)} then type ${cyan(aliasName)}\n`
  );
  console.log(dim("  Your tokens are stored locally in .env.local"));
  console.log(dim("  and are never sent anywhere except to Slack's API.\n"));

  rl.close();
}

main().catch((err) => {
  console.error("\n  Setup failed:", err.message);
  rl.close();
  process.exit(1);
});
